#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 0.10.3.{build}

# branches to build
branches:
  # blacklist
  except:
    - gh-pages

# Do not build on tags (GitHub only)
skip_tags: true

#---------------------------------#
#    environment configuration    #
#---------------------------------#
cache:
  - packages

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input
  - nuget sources add -Name https://dotnet.myget.org/F/dotnet-core/api/v3/index.json -Source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build Configuration, i.e. Debug, Release, etc.
configuration: Release

os: Visual Studio 2017

before_build:
  - dotnet --info
  - msbuild /t:Restore .\src\BenchmarkDotNet.Core\BenchmarkDotNet.Core.csproj
  - msbuild /t:Restore .\src\BenchmarkDotNet.Toolchains.Roslyn\BenchmarkDotNet.Toolchains.Roslyn.csproj
  - msbuild /t:Restore .\src\BenchmarkDotNet\BenchmarkDotNet.csproj
  - msbuild /t:Restore .\src\BenchmarkDotNet.Diagnostics.Windows\BenchmarkDotNet.Diagnostics.Windows.csproj
  - msbuild /t:Restore .\src\BenchmarkDotNet.Toolchains.Uap\BenchmarkDotNet.Toolchains.Uap.csproj

build:
  parallel: true                  # enable MSBuild parallel builds
  project: BenchmarkDotNet.sln    # path to Visual Studio solution or project

after_build:
  - msbuild /t:Pack .\src\BenchmarkDotNet.Core\BenchmarkDotNet.Core.csproj /p:configuration=Release;platform=AnyCPU
  - msbuild /t:Pack .\src\BenchmarkDotNet.Toolchains.Roslyn\BenchmarkDotNet.Toolchains.Roslyn.csproj /p:configuration=Release;platform=AnyCPU
  - msbuild /t:Pack .\src\BenchmarkDotNet\BenchmarkDotNet.csproj /p:configuration=Release;platform=AnyCPU
  - msbuild /t:Pack .\src\BenchmarkDotNet.Diagnostics.Windows\BenchmarkDotNet.Diagnostics.Windows.csproj /p:configuration=Release;platform=AnyCPU
  - msbuild /t:Pack .\src\BenchmarkDotNet.Toolchains.Uap\BenchmarkDotNet.Toolchains.Uap.csproj /p:configuration=Release;platform=AnyCPU
  
#---------------------------------#
#       tests configuration       #
#---------------------------------#
test_script:
  - dotnet test .\tests\BenchmarkDotNet.Tests\BenchmarkDotNet.Tests.csproj --configuration Release --logger:trx;LogFileName=tests-results01.xml
  - ps: .\build\uploadtests.ps1 ".\tests\BenchmarkDotNet.Tests\TestResults\tests-results01.xml"
  - dotnet test .\tests\BenchmarkDotNet.IntegrationTests\BenchmarkDotNet.IntegrationTests.csproj --configuration Release --logger:trx;LogFileName=tests-results02.xml
  - ps: .\build\uploadtests.ps1 ".\tests\BenchmarkDotNet.IntegrationTests\TestResults\tests-results02.xml"

artifacts:
  - path: '**\BenchmarkDotNet.*.nupkg' # find all NuGet packages recursively

