trigger:
  branches:
    include:
    - master
    exclude:
    - gh-pages

name: $(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

jobs:
- template: build/azure-pipelines.job.template.yml
  parameters:
    name: macOS
    vmImage: 'macOS-latest'
    scriptFileName: ./build.sh
