name: generate-changelog
run-name: Generate changelog / ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions: write-all

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v6
      with:
        ref: master

    - name: Checkout changelog
      uses: actions/checkout@v6
      with:
        ref: docs-changelog
        path: docs/_changelog

    - name: Fetch changelog
      run: ./build.cmd docs-fetch --depth 1 --preview
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push changelog
      uses: JamesIves/github-pages-deploy-action@9d877eea73427180ae43cf98e8914934fe157a1a # v4.7.6
      with:
        branch: docs-changelog
        folder: docs/_changelog
        git-config-name: Andrey Akinshin
        git-config-email: andrey.akinshin@gmail.com
        clean: true
